Channel.create(name: "Tech", description: "All things tech")
Channel.create(name: "Politics", description: "All things politics")
Channel.create(name: "Sports", description: "All things sports")
Channel.create(name: "Finance", description: "All things finance")
User.create(phone_number: "2483809188", password: "password")