Channel.create(name: "Tech", description: "All things tech", sources: ["TechCrunch", "TheHackersNews", "newsycombinator"])
Channel.create(name: "Politics", description: "All things politics", sources: ["politicalwire", "BBC", "NPR", "nytimes"])
Channel.create(name: "Sports", description: "All things sports", sources: ["espn"])
Channel.create(name: "Finance", description: "All things finance", sources: ["EconBizFin", "financialtimes"])
User.create(phone_number: "2483809188", password: "password")